version: '3.8'

services:
  slowsurf-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slowsurf-web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=slowsurf.solvy.dev
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.slowsurf.rule=Host(`slowsurf.solvy.dev`)"
      - "traefik.http.routers.slowsurf.entrypoints=websecure"
      - "traefik.http.routers.slowsurf.tls.certresolver=myresolver"
      - "traefik.http.services.slowsurf.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true