version: '3.8'

services:
  slowsurf-web:
    build: .
    container_name: slowsurf-web
    restart: unless-stopped
    networks:
      - traefik
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      
      # Router configuration
      - "traefik.http.routers.slowsurf.rule=Host(`slowsurf.solvy.dev`)"
      - "traefik.http.routers.slowsurf.entrypoints=websecure"
      - "traefik.http.routers.slowsurf.tls=true"
      - "traefik.http.routers.slowsurf.tls.certresolver=myresolver"
      
      # Service configuration
      - "traefik.http.services.slowsurf.loadbalancer.server.port=80"
      
      # HTTP to HTTPS redirect
      - "traefik.http.routers.slowsurf-http.rule=Host(`slowsurf.solvy.dev`)"
      - "traefik.http.routers.slowsurf-http.entrypoints=web"
      - "traefik.http.routers.slowsurf-http.middlewares=redirect-to-https"
      
      # Middleware for HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  traefik:
    external: true